// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketVerkoop.Domain.Context;

namespace TicketVerkoop.Domain.Migrations
{
    [DbContext(typeof(TicketVerkoopDbContext))]
    [Migration("20200513152126_addOneMatch")]
    partial class addOneMatch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Customer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Street");

                    b.Property<string>("Zipcode");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Match", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AwayTeamId");

                    b.Property<double>("BasePriceTicket");

                    b.Property<string>("HomeTeamId");

                    b.Property<DateTime>("MatchDate");

                    b.Property<string>("SeasonId");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AwayTeamId = "2",
                            BasePriceTicket = 15.0,
                            HomeTeamId = "1",
                            MatchDate = new DateTime(2020, 4, 18, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "2",
                            AwayTeamId = "4",
                            BasePriceTicket = 12.0,
                            HomeTeamId = "3",
                            MatchDate = new DateTime(2020, 4, 18, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "3",
                            AwayTeamId = "6",
                            BasePriceTicket = 13.0,
                            HomeTeamId = "5",
                            MatchDate = new DateTime(2020, 4, 18, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "4",
                            AwayTeamId = "1",
                            BasePriceTicket = 15.0,
                            HomeTeamId = "6",
                            MatchDate = new DateTime(2020, 4, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "5",
                            AwayTeamId = "3",
                            BasePriceTicket = 12.0,
                            HomeTeamId = "2",
                            MatchDate = new DateTime(2020, 4, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "6",
                            AwayTeamId = "5",
                            BasePriceTicket = 12.0,
                            HomeTeamId = "4",
                            MatchDate = new DateTime(2020, 4, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "7",
                            AwayTeamId = "2",
                            BasePriceTicket = 15.0,
                            HomeTeamId = "1",
                            MatchDate = new DateTime(2020, 5, 2, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "8",
                            AwayTeamId = "4",
                            BasePriceTicket = 12.0,
                            HomeTeamId = "3",
                            MatchDate = new DateTime(2020, 5, 2, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "9",
                            AwayTeamId = "6",
                            BasePriceTicket = 13.0,
                            HomeTeamId = "5",
                            MatchDate = new DateTime(2020, 5, 2, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "10",
                            AwayTeamId = "6",
                            BasePriceTicket = 15.0,
                            HomeTeamId = "6",
                            MatchDate = new DateTime(2020, 5, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "11",
                            AwayTeamId = "3",
                            BasePriceTicket = 12.0,
                            HomeTeamId = "2",
                            MatchDate = new DateTime(2020, 5, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "12",
                            AwayTeamId = "5",
                            BasePriceTicket = 12.0,
                            HomeTeamId = "4",
                            MatchDate = new DateTime(2020, 5, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "13",
                            AwayTeamId = "2",
                            BasePriceTicket = 15.0,
                            HomeTeamId = "1",
                            MatchDate = new DateTime(2020, 5, 16, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "14",
                            AwayTeamId = "4",
                            BasePriceTicket = 12.0,
                            HomeTeamId = "3",
                            MatchDate = new DateTime(2020, 5, 16, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "15",
                            AwayTeamId = "6",
                            BasePriceTicket = 13.0,
                            HomeTeamId = "5",
                            MatchDate = new DateTime(2020, 5, 16, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "16",
                            AwayTeamId = "1",
                            BasePriceTicket = 15.0,
                            HomeTeamId = "6",
                            MatchDate = new DateTime(2020, 5, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "17",
                            AwayTeamId = "3",
                            BasePriceTicket = 12.0,
                            HomeTeamId = "2",
                            MatchDate = new DateTime(2020, 5, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "18",
                            AwayTeamId = "5",
                            BasePriceTicket = 12.0,
                            HomeTeamId = "4",
                            MatchDate = new DateTime(2020, 5, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        },
                        new
                        {
                            Id = "19",
                            AwayTeamId = "2",
                            BasePriceTicket = 15.0,
                            HomeTeamId = "1",
                            MatchDate = new DateTime(2020, 4, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = "1"
                        });
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.MatchSection", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MatchId");

                    b.Property<int>("OccupiedReservationSeats");

                    b.Property<string>("SectionId");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("SectionId");

                    b.ToTable("MatchSections");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            MatchId = "1",
                            OccupiedReservationSeats = 0,
                            SectionId = "1"
                        },
                        new
                        {
                            Id = "2",
                            MatchId = "1",
                            OccupiedReservationSeats = 0,
                            SectionId = "2"
                        },
                        new
                        {
                            Id = "3",
                            MatchId = "1",
                            OccupiedReservationSeats = 0,
                            SectionId = "3"
                        },
                        new
                        {
                            Id = "4",
                            MatchId = "1",
                            OccupiedReservationSeats = 0,
                            SectionId = "4"
                        },
                        new
                        {
                            Id = "5",
                            MatchId = "1",
                            OccupiedReservationSeats = 0,
                            SectionId = "5"
                        },
                        new
                        {
                            Id = "6",
                            MatchId = "1",
                            OccupiedReservationSeats = 0,
                            SectionId = "6"
                        },
                        new
                        {
                            Id = "7",
                            MatchId = "1",
                            OccupiedReservationSeats = 0,
                            SectionId = "7"
                        },
                        new
                        {
                            Id = "8",
                            MatchId = "1",
                            OccupiedReservationSeats = 0,
                            SectionId = "8"
                        },
                        new
                        {
                            Id = "9",
                            MatchId = "2",
                            OccupiedReservationSeats = 0,
                            SectionId = "17"
                        },
                        new
                        {
                            Id = "10",
                            MatchId = "2",
                            OccupiedReservationSeats = 0,
                            SectionId = "18"
                        },
                        new
                        {
                            Id = "11",
                            MatchId = "2",
                            OccupiedReservationSeats = 0,
                            SectionId = "19"
                        },
                        new
                        {
                            Id = "12",
                            MatchId = "2",
                            OccupiedReservationSeats = 0,
                            SectionId = "20"
                        },
                        new
                        {
                            Id = "13",
                            MatchId = "2",
                            OccupiedReservationSeats = 0,
                            SectionId = "21"
                        },
                        new
                        {
                            Id = "14",
                            MatchId = "2",
                            OccupiedReservationSeats = 0,
                            SectionId = "22"
                        },
                        new
                        {
                            Id = "15",
                            MatchId = "2",
                            OccupiedReservationSeats = 0,
                            SectionId = "23"
                        },
                        new
                        {
                            Id = "16",
                            MatchId = "2",
                            OccupiedReservationSeats = 0,
                            SectionId = "24"
                        },
                        new
                        {
                            Id = "17",
                            MatchId = "3",
                            OccupiedReservationSeats = 0,
                            SectionId = "33"
                        },
                        new
                        {
                            Id = "18",
                            MatchId = "3",
                            OccupiedReservationSeats = 0,
                            SectionId = "34"
                        },
                        new
                        {
                            Id = "19",
                            MatchId = "3",
                            OccupiedReservationSeats = 0,
                            SectionId = "35"
                        },
                        new
                        {
                            Id = "20",
                            MatchId = "3",
                            OccupiedReservationSeats = 0,
                            SectionId = "36"
                        },
                        new
                        {
                            Id = "21",
                            MatchId = "3",
                            OccupiedReservationSeats = 0,
                            SectionId = "37"
                        },
                        new
                        {
                            Id = "22",
                            MatchId = "3",
                            OccupiedReservationSeats = 0,
                            SectionId = "38"
                        },
                        new
                        {
                            Id = "23",
                            MatchId = "3",
                            OccupiedReservationSeats = 0,
                            SectionId = "39"
                        },
                        new
                        {
                            Id = "24",
                            MatchId = "3",
                            OccupiedReservationSeats = 0,
                            SectionId = "40"
                        },
                        new
                        {
                            Id = "25",
                            MatchId = "4",
                            OccupiedReservationSeats = 0,
                            SectionId = "41"
                        },
                        new
                        {
                            Id = "26",
                            MatchId = "4",
                            OccupiedReservationSeats = 0,
                            SectionId = "42"
                        },
                        new
                        {
                            Id = "27",
                            MatchId = "4",
                            OccupiedReservationSeats = 0,
                            SectionId = "43"
                        },
                        new
                        {
                            Id = "28",
                            MatchId = "4",
                            OccupiedReservationSeats = 0,
                            SectionId = "44"
                        },
                        new
                        {
                            Id = "29",
                            MatchId = "4",
                            OccupiedReservationSeats = 0,
                            SectionId = "45"
                        },
                        new
                        {
                            Id = "30",
                            MatchId = "4",
                            OccupiedReservationSeats = 0,
                            SectionId = "46"
                        },
                        new
                        {
                            Id = "31",
                            MatchId = "4",
                            OccupiedReservationSeats = 0,
                            SectionId = "17"
                        },
                        new
                        {
                            Id = "32",
                            MatchId = "4",
                            OccupiedReservationSeats = 0,
                            SectionId = "48"
                        },
                        new
                        {
                            Id = "33",
                            MatchId = "5",
                            OccupiedReservationSeats = 0,
                            SectionId = "9"
                        },
                        new
                        {
                            Id = "34",
                            MatchId = "5",
                            OccupiedReservationSeats = 0,
                            SectionId = "10"
                        },
                        new
                        {
                            Id = "35",
                            MatchId = "5",
                            OccupiedReservationSeats = 0,
                            SectionId = "11"
                        },
                        new
                        {
                            Id = "36",
                            MatchId = "5",
                            OccupiedReservationSeats = 0,
                            SectionId = "12"
                        },
                        new
                        {
                            Id = "37",
                            MatchId = "5",
                            OccupiedReservationSeats = 0,
                            SectionId = "13"
                        },
                        new
                        {
                            Id = "38",
                            MatchId = "5",
                            OccupiedReservationSeats = 0,
                            SectionId = "14"
                        },
                        new
                        {
                            Id = "39",
                            MatchId = "5",
                            OccupiedReservationSeats = 0,
                            SectionId = "15"
                        },
                        new
                        {
                            Id = "40",
                            MatchId = "5",
                            OccupiedReservationSeats = 0,
                            SectionId = "16"
                        },
                        new
                        {
                            Id = "41",
                            MatchId = "6",
                            OccupiedReservationSeats = 0,
                            SectionId = "25"
                        },
                        new
                        {
                            Id = "42",
                            MatchId = "6",
                            OccupiedReservationSeats = 0,
                            SectionId = "26"
                        },
                        new
                        {
                            Id = "43",
                            MatchId = "6",
                            OccupiedReservationSeats = 0,
                            SectionId = "27"
                        },
                        new
                        {
                            Id = "44",
                            MatchId = "6",
                            OccupiedReservationSeats = 0,
                            SectionId = "28"
                        },
                        new
                        {
                            Id = "45",
                            MatchId = "6",
                            OccupiedReservationSeats = 0,
                            SectionId = "29"
                        },
                        new
                        {
                            Id = "46",
                            MatchId = "6",
                            OccupiedReservationSeats = 0,
                            SectionId = "30"
                        },
                        new
                        {
                            Id = "47",
                            MatchId = "6",
                            OccupiedReservationSeats = 0,
                            SectionId = "31"
                        },
                        new
                        {
                            Id = "48",
                            MatchId = "6",
                            OccupiedReservationSeats = 0,
                            SectionId = "32"
                        },
                        new
                        {
                            Id = "49",
                            MatchId = "7",
                            OccupiedReservationSeats = 0,
                            SectionId = "1"
                        },
                        new
                        {
                            Id = "50",
                            MatchId = "7",
                            OccupiedReservationSeats = 0,
                            SectionId = "2"
                        },
                        new
                        {
                            Id = "51",
                            MatchId = "7",
                            OccupiedReservationSeats = 0,
                            SectionId = "3"
                        },
                        new
                        {
                            Id = "52",
                            MatchId = "7",
                            OccupiedReservationSeats = 0,
                            SectionId = "4"
                        },
                        new
                        {
                            Id = "53",
                            MatchId = "7",
                            OccupiedReservationSeats = 0,
                            SectionId = "5"
                        },
                        new
                        {
                            Id = "54",
                            MatchId = "7",
                            OccupiedReservationSeats = 0,
                            SectionId = "6"
                        },
                        new
                        {
                            Id = "55",
                            MatchId = "7",
                            OccupiedReservationSeats = 0,
                            SectionId = "7"
                        },
                        new
                        {
                            Id = "56",
                            MatchId = "7",
                            OccupiedReservationSeats = 0,
                            SectionId = "8"
                        },
                        new
                        {
                            Id = "57",
                            MatchId = "8",
                            OccupiedReservationSeats = 0,
                            SectionId = "17"
                        },
                        new
                        {
                            Id = "58",
                            MatchId = "8",
                            OccupiedReservationSeats = 0,
                            SectionId = "18"
                        },
                        new
                        {
                            Id = "59",
                            MatchId = "8",
                            OccupiedReservationSeats = 0,
                            SectionId = "19"
                        },
                        new
                        {
                            Id = "60",
                            MatchId = "8",
                            OccupiedReservationSeats = 0,
                            SectionId = "20"
                        },
                        new
                        {
                            Id = "61",
                            MatchId = "8",
                            OccupiedReservationSeats = 0,
                            SectionId = "21"
                        },
                        new
                        {
                            Id = "62",
                            MatchId = "8",
                            OccupiedReservationSeats = 0,
                            SectionId = "22"
                        },
                        new
                        {
                            Id = "63",
                            MatchId = "8",
                            OccupiedReservationSeats = 0,
                            SectionId = "23"
                        },
                        new
                        {
                            Id = "64",
                            MatchId = "8",
                            OccupiedReservationSeats = 0,
                            SectionId = "24"
                        },
                        new
                        {
                            Id = "65",
                            MatchId = "9",
                            OccupiedReservationSeats = 0,
                            SectionId = "33"
                        },
                        new
                        {
                            Id = "66",
                            MatchId = "9",
                            OccupiedReservationSeats = 0,
                            SectionId = "34"
                        },
                        new
                        {
                            Id = "67",
                            MatchId = "9",
                            OccupiedReservationSeats = 0,
                            SectionId = "35"
                        },
                        new
                        {
                            Id = "68",
                            MatchId = "9",
                            OccupiedReservationSeats = 0,
                            SectionId = "36"
                        },
                        new
                        {
                            Id = "69",
                            MatchId = "9",
                            OccupiedReservationSeats = 0,
                            SectionId = "37"
                        },
                        new
                        {
                            Id = "70",
                            MatchId = "9",
                            OccupiedReservationSeats = 0,
                            SectionId = "38"
                        },
                        new
                        {
                            Id = "71",
                            MatchId = "9",
                            OccupiedReservationSeats = 0,
                            SectionId = "39"
                        },
                        new
                        {
                            Id = "72",
                            MatchId = "9",
                            OccupiedReservationSeats = 0,
                            SectionId = "40"
                        },
                        new
                        {
                            Id = "73",
                            MatchId = "10",
                            OccupiedReservationSeats = 0,
                            SectionId = "41"
                        },
                        new
                        {
                            Id = "74",
                            MatchId = "10",
                            OccupiedReservationSeats = 0,
                            SectionId = "42"
                        },
                        new
                        {
                            Id = "75",
                            MatchId = "10",
                            OccupiedReservationSeats = 0,
                            SectionId = "43"
                        },
                        new
                        {
                            Id = "76",
                            MatchId = "10",
                            OccupiedReservationSeats = 0,
                            SectionId = "44"
                        },
                        new
                        {
                            Id = "77",
                            MatchId = "10",
                            OccupiedReservationSeats = 0,
                            SectionId = "45"
                        },
                        new
                        {
                            Id = "78",
                            MatchId = "10",
                            OccupiedReservationSeats = 0,
                            SectionId = "46"
                        },
                        new
                        {
                            Id = "79",
                            MatchId = "10",
                            OccupiedReservationSeats = 0,
                            SectionId = "17"
                        },
                        new
                        {
                            Id = "80",
                            MatchId = "10",
                            OccupiedReservationSeats = 0,
                            SectionId = "48"
                        },
                        new
                        {
                            Id = "81",
                            MatchId = "11",
                            OccupiedReservationSeats = 0,
                            SectionId = "9"
                        },
                        new
                        {
                            Id = "82",
                            MatchId = "11",
                            OccupiedReservationSeats = 0,
                            SectionId = "10"
                        },
                        new
                        {
                            Id = "83",
                            MatchId = "11",
                            OccupiedReservationSeats = 0,
                            SectionId = "11"
                        },
                        new
                        {
                            Id = "84",
                            MatchId = "11",
                            OccupiedReservationSeats = 0,
                            SectionId = "12"
                        },
                        new
                        {
                            Id = "85",
                            MatchId = "11",
                            OccupiedReservationSeats = 0,
                            SectionId = "13"
                        },
                        new
                        {
                            Id = "86",
                            MatchId = "11",
                            OccupiedReservationSeats = 0,
                            SectionId = "14"
                        },
                        new
                        {
                            Id = "87",
                            MatchId = "11",
                            OccupiedReservationSeats = 0,
                            SectionId = "15"
                        },
                        new
                        {
                            Id = "88",
                            MatchId = "11",
                            OccupiedReservationSeats = 0,
                            SectionId = "16"
                        },
                        new
                        {
                            Id = "89",
                            MatchId = "12",
                            OccupiedReservationSeats = 0,
                            SectionId = "25"
                        },
                        new
                        {
                            Id = "90",
                            MatchId = "12",
                            OccupiedReservationSeats = 0,
                            SectionId = "26"
                        },
                        new
                        {
                            Id = "91",
                            MatchId = "12",
                            OccupiedReservationSeats = 0,
                            SectionId = "27"
                        },
                        new
                        {
                            Id = "92",
                            MatchId = "12",
                            OccupiedReservationSeats = 0,
                            SectionId = "28"
                        },
                        new
                        {
                            Id = "93",
                            MatchId = "12",
                            OccupiedReservationSeats = 0,
                            SectionId = "29"
                        },
                        new
                        {
                            Id = "94",
                            MatchId = "12",
                            OccupiedReservationSeats = 0,
                            SectionId = "30"
                        },
                        new
                        {
                            Id = "95",
                            MatchId = "12",
                            OccupiedReservationSeats = 0,
                            SectionId = "31"
                        },
                        new
                        {
                            Id = "96",
                            MatchId = "12",
                            OccupiedReservationSeats = 0,
                            SectionId = "32"
                        },
                        new
                        {
                            Id = "97",
                            MatchId = "13",
                            OccupiedReservationSeats = 0,
                            SectionId = "1"
                        },
                        new
                        {
                            Id = "98",
                            MatchId = "13",
                            OccupiedReservationSeats = 0,
                            SectionId = "2"
                        },
                        new
                        {
                            Id = "99",
                            MatchId = "13",
                            OccupiedReservationSeats = 0,
                            SectionId = "3"
                        },
                        new
                        {
                            Id = "100",
                            MatchId = "13",
                            OccupiedReservationSeats = 0,
                            SectionId = "4"
                        },
                        new
                        {
                            Id = "101",
                            MatchId = "13",
                            OccupiedReservationSeats = 0,
                            SectionId = "5"
                        },
                        new
                        {
                            Id = "102",
                            MatchId = "13",
                            OccupiedReservationSeats = 0,
                            SectionId = "6"
                        },
                        new
                        {
                            Id = "103",
                            MatchId = "13",
                            OccupiedReservationSeats = 0,
                            SectionId = "7"
                        },
                        new
                        {
                            Id = "104",
                            MatchId = "13",
                            OccupiedReservationSeats = 0,
                            SectionId = "8"
                        },
                        new
                        {
                            Id = "105",
                            MatchId = "14",
                            OccupiedReservationSeats = 0,
                            SectionId = "17"
                        },
                        new
                        {
                            Id = "106",
                            MatchId = "14",
                            OccupiedReservationSeats = 0,
                            SectionId = "18"
                        },
                        new
                        {
                            Id = "107",
                            MatchId = "14",
                            OccupiedReservationSeats = 0,
                            SectionId = "19"
                        },
                        new
                        {
                            Id = "108",
                            MatchId = "14",
                            OccupiedReservationSeats = 0,
                            SectionId = "20"
                        },
                        new
                        {
                            Id = "109",
                            MatchId = "14",
                            OccupiedReservationSeats = 0,
                            SectionId = "21"
                        },
                        new
                        {
                            Id = "110",
                            MatchId = "14",
                            OccupiedReservationSeats = 0,
                            SectionId = "22"
                        },
                        new
                        {
                            Id = "111",
                            MatchId = "14",
                            OccupiedReservationSeats = 0,
                            SectionId = "23"
                        },
                        new
                        {
                            Id = "112",
                            MatchId = "14",
                            OccupiedReservationSeats = 0,
                            SectionId = "24"
                        },
                        new
                        {
                            Id = "113",
                            MatchId = "15",
                            OccupiedReservationSeats = 0,
                            SectionId = "33"
                        },
                        new
                        {
                            Id = "114",
                            MatchId = "15",
                            OccupiedReservationSeats = 0,
                            SectionId = "34"
                        },
                        new
                        {
                            Id = "115",
                            MatchId = "15",
                            OccupiedReservationSeats = 0,
                            SectionId = "35"
                        },
                        new
                        {
                            Id = "116",
                            MatchId = "15",
                            OccupiedReservationSeats = 0,
                            SectionId = "36"
                        },
                        new
                        {
                            Id = "117",
                            MatchId = "15",
                            OccupiedReservationSeats = 0,
                            SectionId = "37"
                        },
                        new
                        {
                            Id = "118",
                            MatchId = "15",
                            OccupiedReservationSeats = 0,
                            SectionId = "38"
                        },
                        new
                        {
                            Id = "119",
                            MatchId = "15",
                            OccupiedReservationSeats = 0,
                            SectionId = "39"
                        },
                        new
                        {
                            Id = "120",
                            MatchId = "15",
                            OccupiedReservationSeats = 0,
                            SectionId = "40"
                        },
                        new
                        {
                            Id = "121",
                            MatchId = "16",
                            OccupiedReservationSeats = 0,
                            SectionId = "41"
                        },
                        new
                        {
                            Id = "122",
                            MatchId = "16",
                            OccupiedReservationSeats = 0,
                            SectionId = "42"
                        },
                        new
                        {
                            Id = "123",
                            MatchId = "16",
                            OccupiedReservationSeats = 0,
                            SectionId = "43"
                        },
                        new
                        {
                            Id = "124",
                            MatchId = "16",
                            OccupiedReservationSeats = 0,
                            SectionId = "44"
                        },
                        new
                        {
                            Id = "125",
                            MatchId = "16",
                            OccupiedReservationSeats = 0,
                            SectionId = "45"
                        },
                        new
                        {
                            Id = "126",
                            MatchId = "16",
                            OccupiedReservationSeats = 0,
                            SectionId = "46"
                        },
                        new
                        {
                            Id = "127",
                            MatchId = "16",
                            OccupiedReservationSeats = 0,
                            SectionId = "17"
                        },
                        new
                        {
                            Id = "128",
                            MatchId = "16",
                            OccupiedReservationSeats = 0,
                            SectionId = "48"
                        },
                        new
                        {
                            Id = "129",
                            MatchId = "17",
                            OccupiedReservationSeats = 0,
                            SectionId = "9"
                        },
                        new
                        {
                            Id = "130",
                            MatchId = "17",
                            OccupiedReservationSeats = 0,
                            SectionId = "10"
                        },
                        new
                        {
                            Id = "131",
                            MatchId = "17",
                            OccupiedReservationSeats = 0,
                            SectionId = "11"
                        },
                        new
                        {
                            Id = "132",
                            MatchId = "17",
                            OccupiedReservationSeats = 0,
                            SectionId = "12"
                        },
                        new
                        {
                            Id = "133",
                            MatchId = "17",
                            OccupiedReservationSeats = 0,
                            SectionId = "13"
                        },
                        new
                        {
                            Id = "134",
                            MatchId = "17",
                            OccupiedReservationSeats = 0,
                            SectionId = "14"
                        },
                        new
                        {
                            Id = "135",
                            MatchId = "17",
                            OccupiedReservationSeats = 0,
                            SectionId = "15"
                        },
                        new
                        {
                            Id = "136",
                            MatchId = "17",
                            OccupiedReservationSeats = 0,
                            SectionId = "16"
                        },
                        new
                        {
                            Id = "137",
                            MatchId = "18",
                            OccupiedReservationSeats = 0,
                            SectionId = "25"
                        },
                        new
                        {
                            Id = "138",
                            MatchId = "18",
                            OccupiedReservationSeats = 0,
                            SectionId = "26"
                        },
                        new
                        {
                            Id = "139",
                            MatchId = "18",
                            OccupiedReservationSeats = 0,
                            SectionId = "27"
                        },
                        new
                        {
                            Id = "140",
                            MatchId = "18",
                            OccupiedReservationSeats = 0,
                            SectionId = "28"
                        },
                        new
                        {
                            Id = "141",
                            MatchId = "18",
                            OccupiedReservationSeats = 0,
                            SectionId = "29"
                        },
                        new
                        {
                            Id = "142",
                            MatchId = "18",
                            OccupiedReservationSeats = 0,
                            SectionId = "30"
                        },
                        new
                        {
                            Id = "143",
                            MatchId = "18",
                            OccupiedReservationSeats = 0,
                            SectionId = "31"
                        },
                        new
                        {
                            Id = "144",
                            MatchId = "18",
                            OccupiedReservationSeats = 0,
                            SectionId = "32"
                        },
                        new
                        {
                            Id = "145",
                            MatchId = "19",
                            OccupiedReservationSeats = 0,
                            SectionId = "1"
                        },
                        new
                        {
                            Id = "146",
                            MatchId = "19",
                            OccupiedReservationSeats = 0,
                            SectionId = "2"
                        },
                        new
                        {
                            Id = "147",
                            MatchId = "19",
                            OccupiedReservationSeats = 0,
                            SectionId = "3"
                        },
                        new
                        {
                            Id = "148",
                            MatchId = "19",
                            OccupiedReservationSeats = 0,
                            SectionId = "4"
                        },
                        new
                        {
                            Id = "149",
                            MatchId = "19",
                            OccupiedReservationSeats = 0,
                            SectionId = "5"
                        },
                        new
                        {
                            Id = "150",
                            MatchId = "19",
                            OccupiedReservationSeats = 0,
                            SectionId = "6"
                        },
                        new
                        {
                            Id = "151",
                            MatchId = "19",
                            OccupiedReservationSeats = 0,
                            SectionId = "7"
                        },
                        new
                        {
                            Id = "152",
                            MatchId = "19",
                            OccupiedReservationSeats = 0,
                            SectionId = "8"
                        });
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Reservation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomerId");

                    b.Property<string>("MatchSectionId");

                    b.Property<int>("NumberOfTickets");

                    b.Property<double>("Price");

                    b.Property<DateTime>("ReservationDate");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MatchSectionId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Season", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            EndDate = new DateTime(2020, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2019, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "2",
                            EndDate = new DateTime(2021, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "3",
                            EndDate = new DateTime(2022, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Section", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.Property<string>("Name");

                    b.Property<int>("OccupiedSubscriptionSeats");

                    b.Property<double>("PriceFactor");

                    b.Property<int>("Ring");

                    b.Property<string>("StadiumId");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "1"
                        },
                        new
                        {
                            Id = "2",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "1"
                        },
                        new
                        {
                            Id = "3",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "1"
                        },
                        new
                        {
                            Id = "4",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "1"
                        },
                        new
                        {
                            Id = "5",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "1"
                        },
                        new
                        {
                            Id = "6",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "1"
                        },
                        new
                        {
                            Id = "7",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "1"
                        },
                        new
                        {
                            Id = "8",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "1"
                        },
                        new
                        {
                            Id = "9",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "2"
                        },
                        new
                        {
                            Id = "10",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "2"
                        },
                        new
                        {
                            Id = "11",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "2"
                        },
                        new
                        {
                            Id = "12",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "2"
                        },
                        new
                        {
                            Id = "13",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "2"
                        },
                        new
                        {
                            Id = "14",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "2"
                        },
                        new
                        {
                            Id = "15",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "2"
                        },
                        new
                        {
                            Id = "16",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "2"
                        },
                        new
                        {
                            Id = "17",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "3"
                        },
                        new
                        {
                            Id = "18",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "3"
                        },
                        new
                        {
                            Id = "19",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "3"
                        },
                        new
                        {
                            Id = "20",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "3"
                        },
                        new
                        {
                            Id = "21",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "3"
                        },
                        new
                        {
                            Id = "22",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "3"
                        },
                        new
                        {
                            Id = "23",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "3"
                        },
                        new
                        {
                            Id = "24",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "3"
                        },
                        new
                        {
                            Id = "25",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "4"
                        },
                        new
                        {
                            Id = "26",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "4"
                        },
                        new
                        {
                            Id = "27",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "4"
                        },
                        new
                        {
                            Id = "28",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "4"
                        },
                        new
                        {
                            Id = "29",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "4"
                        },
                        new
                        {
                            Id = "30",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "4"
                        },
                        new
                        {
                            Id = "31",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "4"
                        },
                        new
                        {
                            Id = "32",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "4"
                        },
                        new
                        {
                            Id = "33",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "5"
                        },
                        new
                        {
                            Id = "34",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "5"
                        },
                        new
                        {
                            Id = "35",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "5"
                        },
                        new
                        {
                            Id = "36",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "5"
                        },
                        new
                        {
                            Id = "37",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "5"
                        },
                        new
                        {
                            Id = "38",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "5"
                        },
                        new
                        {
                            Id = "39",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "5"
                        },
                        new
                        {
                            Id = "40",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "5"
                        },
                        new
                        {
                            Id = "41",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "6"
                        },
                        new
                        {
                            Id = "42",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "6"
                        },
                        new
                        {
                            Id = "43",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 0.80000000000000004,
                            Ring = 0,
                            StadiumId = "6"
                        },
                        new
                        {
                            Id = "44",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.2,
                            Ring = 0,
                            StadiumId = "6"
                        },
                        new
                        {
                            Id = "45",
                            Capacity = 1000,
                            Name = "North",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "6"
                        },
                        new
                        {
                            Id = "46",
                            Capacity = 3000,
                            Name = "East",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "6"
                        },
                        new
                        {
                            Id = "47",
                            Capacity = 1000,
                            Name = "South",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.1000000000000001,
                            Ring = 1,
                            StadiumId = "6"
                        },
                        new
                        {
                            Id = "48",
                            Capacity = 3000,
                            Name = "West",
                            OccupiedSubscriptionSeats = 0,
                            PriceFactor = 1.5,
                            Ring = 1,
                            StadiumId = "6"
                        });
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Stadium", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.Property<string>("Street");

                    b.Property<string>("Zipcode");

                    b.HasKey("Id");

                    b.ToTable("Stadia");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            City = "Brugge",
                            Country = "België",
                            Name = "Jan Breydelstadion",
                            Street = "Olympialaan 74",
                            Zipcode = "8000"
                        },
                        new
                        {
                            Id = "2",
                            City = "Oostende",
                            Country = "België",
                            Name = "Albertparkstadion",
                            Street = "Leopold Van Tyghemlaan 62",
                            Zipcode = "8400"
                        },
                        new
                        {
                            Id = "3",
                            City = "Brussel",
                            Country = "België",
                            Name = "Constant Vanden Stock stadion",
                            Street = "Theo Verbeecklaan 2",
                            Zipcode = "1070"
                        },
                        new
                        {
                            Id = "4",
                            City = "Waregem",
                            Country = "België",
                            Name = "Regenboogstadion",
                            Street = "Zuiderlaan 17",
                            Zipcode = "8790"
                        },
                        new
                        {
                            Id = "5",
                            City = "Genk",
                            Country = "België",
                            Name = "Cristal Arena",
                            Street = "Stadionplein",
                            Zipcode = "3600"
                        },
                        new
                        {
                            Id = "6",
                            City = "Gentbrugge",
                            Country = "België",
                            Name = "Ghelamco Arena",
                            Street = "Bruiloftstraat 42",
                            Zipcode = "9050"
                        });
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomerId");

                    b.Property<double>("Price");

                    b.Property<string>("SeasonId");

                    b.Property<string>("SectionId");

                    b.Property<string>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SectionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Team", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Logo");

                    b.Property<string>("Name");

                    b.Property<string>("StadiumId");

                    b.Property<double>("SubscriptionPrice");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Logo = "/images/Club_Brugge.png",
                            Name = "Club Brugge",
                            StadiumId = "1",
                            SubscriptionPrice = 450.0
                        },
                        new
                        {
                            Id = "2",
                            Logo = "/images/Oostende.png",
                            Name = "Oostende",
                            StadiumId = "2",
                            SubscriptionPrice = 200.0
                        },
                        new
                        {
                            Id = "3",
                            Logo = "/images/RSC_Anderlecht.png",
                            Name = "RSC Anderlecht",
                            StadiumId = "3",
                            SubscriptionPrice = 500.0
                        },
                        new
                        {
                            Id = "4",
                            Logo = "/images/Zulte_Waregem.png",
                            Name = "Zulte Waregem",
                            StadiumId = "4",
                            SubscriptionPrice = 250.0
                        },
                        new
                        {
                            Id = "5",
                            Logo = "/images/Genk.png",
                            Name = "Genk",
                            StadiumId = "5",
                            SubscriptionPrice = 350.0
                        },
                        new
                        {
                            Id = "6",
                            Logo = "/images/AA_Gent.png",
                            Name = "AA Gent",
                            StadiumId = "6",
                            SubscriptionPrice = 300.0
                        });
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Match", b =>
                {
                    b.HasOne("TicketVerkoop.Domain.Context.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId");

                    b.HasOne("TicketVerkoop.Domain.Context.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId");

                    b.HasOne("TicketVerkoop.Domain.Context.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId");
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.MatchSection", b =>
                {
                    b.HasOne("TicketVerkoop.Domain.Context.Match", "Match")
                        .WithMany("MatchSections")
                        .HasForeignKey("MatchId");

                    b.HasOne("TicketVerkoop.Domain.Context.Section", "Section")
                        .WithMany("MatchSections")
                        .HasForeignKey("SectionId");
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Reservation", b =>
                {
                    b.HasOne("TicketVerkoop.Domain.Context.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId");

                    b.HasOne("TicketVerkoop.Domain.Context.MatchSection", "MatchSection")
                        .WithMany("Reservations")
                        .HasForeignKey("MatchSectionId");
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Section", b =>
                {
                    b.HasOne("TicketVerkoop.Domain.Context.Stadium", "Stadium")
                        .WithMany("Sections")
                        .HasForeignKey("StadiumId");
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Subscription", b =>
                {
                    b.HasOne("TicketVerkoop.Domain.Context.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId");

                    b.HasOne("TicketVerkoop.Domain.Context.Season", "Season")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SeasonId");

                    b.HasOne("TicketVerkoop.Domain.Context.Section", "Section")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SectionId");

                    b.HasOne("TicketVerkoop.Domain.Context.Team", "Team")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("TicketVerkoop.Domain.Context.Team", b =>
                {
                    b.HasOne("TicketVerkoop.Domain.Context.Stadium", "Stadium")
                        .WithMany("Teams")
                        .HasForeignKey("StadiumId");
                });
#pragma warning restore 612, 618
        }
    }
}
